# Debug mode
debug: false
# Storage system (Only mysql is supported for now)
storage:
  type: mysql
  mysql:
    prefix: "host_"
    hostname: "localhost:3306"
    database: "minecraft"
    username: "user"
    password: "pass"
# Messaging system
messaging:
  # Available types:
  #   RabbitMQ: Recommended ! 100% Working !
  #     ! RabbitMQ's connection need to be setup in messaging.rabbit-mq section !
  #   Plugin: Not fully working, currently not recommended
  #   None: If you only need the API, without other plugin functions
  type: None
  rabbit-mq:
    prefix: "host."
    hostname: "localhost"
    port: 5672
    username: "user"
    password: "pass"
# The type can be "host" for a game server or "lobby" for a lobby server
# If you only need the API you can set "none"
server-type: lobby
